import JSZip from 'jszip';
import { NextResponse } from 'next/server';
import { buildEmbedUrl, extractPhotoItemsFromHtml, isInstagramPhotoUrl } from '../../../lib/photo';
import { decodeInstagramUrl } from '../../../lib/download';

export const runtime = 'nodejs';
export const maxDuration = 60;
const headers = { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/126.0.0.0 Safari/537.36', Accept: 'text/html,application/xhtml+xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-US,en;q=0.9', Referer: 'https://www.instagram.com/' };
type MediaItem={id:string;url:string;filename:string;type:'image'|'video';width:number|null;height:number|null};

function videoItems(html:string,shortcode:string):MediaItem[]{const found:MediaItem[]=[];const seen=new Set<string>();const patterns=[/"video_url"\s*:\s*"((?:\\.|[^"\\])+)"/gi,/"url"\s*:\s*"((?:\\.|[^"\\])*\.mp4(?:\\.|[^"\\])*)"/gi];for(const pattern of patterns){let match;while((match=pattern.exec(html))!==null){const url=decodeInstagramUrl(match[1]);if(!url.startsWith('http')||seen.has(url))continue;seen.add(url);found.push({id:`${shortcode}-video-${found.length+1}`,url,filename:`${shortcode}-${found.length+1}.mp4`,type:'video',width:null,height:null});if(found.length>=10)return found;}}return found;}
async function extract(url:string){const shortcode=url.match(/instagram\.com\/p\/([A-Za-z0-9_-]+)/i)?.[1]||'instagram-carousel';let html='';for(const target of [url.replace(/\/+$/,''),buildEmbedUrl(url)]){const response=await fetch(target,{headers,cache:'no-store'}).catch(()=>null);if(!response?.ok)continue;html=await response.text();const photos=extractPhotoItemsFromHtml(html,url).items.map(item=>({...item,type:'image' as const}));const videos=videoItems(html,shortcode);const combined=[...photos,...videos];if(combined.length)return Array.from(new Map(combined.map(item=>[item.url,item])).values()).slice(0,20);}return [] as MediaItem[];}
function safeFilename(value:string,index:number,type:'image'|'video'){const cleaned=value.replace(/[^a-zA-Z0-9._-]/g,'-');return cleaned.includes('.')?cleaned:`carousel-${index+1}.${type==='video'?'mp4':'jpg'}`;}

export async function POST(request:Request){const body=await request.json().catch(()=>null);const url=typeof body?.url==='string'?body.url.trim():'';const action=body?.action==='download'?'download':'inspect';if(!isInstagramPhotoUrl(url))return NextResponse.json({error:'Paste a valid public Instagram carousel post URL.'},{status:400});const items=await extract(url);if(!items.length)return NextResponse.json({error:'No public carousel media was available for this link.'},{status:422});if(action==='inspect'){return NextResponse.json({success:true,count:items.length,items:items.map(item=>({id:item.id,type:item.type,width:item.width,height:item.height,previewUrl:`/api/proxy?url=${encodeURIComponent(item.url)}`}))});}
  const zip=new JSZip();let totalBytes=0;let added=0;for(const[itemIndex,item]of items.entries()){const response=await fetch(item.url,{headers:{...headers,Accept:'*/*'}}).catch(()=>null);if(!response?.ok)continue;const data=await response.arrayBuffer();totalBytes+=data.byteLength;if(totalBytes>80*1024*1024)return NextResponse.json({error:'This carousel is too large to create safely. Try downloading items individually.'},{status:413});zip.file(safeFilename(item.filename,itemIndex,item.type),data);added+=1;}if(!added)return NextResponse.json({error:'Carousel items were found but could not be downloaded.'},{status:502});const buffer=await zip.generateAsync({type:'nodebuffer',compression:'DEFLATE',compressionOptions:{level:6}});return new Response(buffer,{headers:{'Content-Type':'application/zip','Content-Disposition':'attachment; filename="instagram-carousel.zip"','Cache-Control':'no-store'}});}
