'use client';
import { useState } from 'react';
import { trackEvent } from '../components/Analytics';

type Result = { validFormat: boolean; contentType?: string; normalizedUrl?: string; status: string; responseTimeMs?: number; message: string };
export default function LinkCheckerClient() {
  const [url,setUrl]=useState(''); const [result,setResult]=useState<Result|null>(null); const [loading,setLoading]=useState(false);
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setResult(null);trackEvent('link_checker_submit');try{const response=await fetch('/api/instagram-link-check',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:url.trim()})});const data=await response.json();setResult(data);trackEvent('link_checker_result',{result_status:data.status||'unknown'});}catch{setResult({validFormat:false,status:'network_error',message:'A network error occurred. Please try again.'});}finally{setLoading(false)}}
  const positive=result?.status==='publicly_available';
  return <div className="space-y-5"><form onSubmit={submit} className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:grid-cols-[1fr_auto]"><label htmlFor="check-url" className="sr-only">Instagram URL</label><input id="check-url" type="url" required value={url} onChange={e=>setUrl(e.target.value)} placeholder="Paste an Instagram Reel, post, or Story URL" className="min-h-14 rounded-xl border border-slate-200 bg-slate-50 px-4 text-sm outline-none focus:border-emerald-500"/><button disabled={loading} className="min-h-14 rounded-xl bg-slate-950 px-7 text-sm font-bold text-white hover:bg-emerald-800 disabled:opacity-60">{loading?'Checking…':'Check link'}</button></form>{result?<section className={`rounded-2xl border p-6 shadow-sm ${positive?'border-emerald-200 bg-emerald-50':'border-amber-200 bg-amber-50'}`}><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-3 py-1 text-xs font-black uppercase ${positive?'bg-emerald-700 text-white':'bg-amber-700 text-white'}`}>{result.status.replace(/_/g,' ')}</span>{result.contentType?<span className="rounded-full bg-white px-3 py-1 text-xs font-bold text-slate-700">{result.contentType}</span>:null}</div><h2 className="mt-4 text-xl font-bold text-slate-950">{result.message}</h2><dl className="mt-5 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="font-bold text-slate-500">Valid format</dt><dd className="mt-1 text-slate-900">{result.validFormat?'Yes':'No'}</dd></div>{typeof result.responseTimeMs==='number'?<div><dt className="font-bold text-slate-500">Server check time</dt><dd className="mt-1 text-slate-900">{result.responseTimeMs} ms</dd></div>:null}</dl></section>:null}</div>;
}
